### PR TITLE
manifold.xyz suggested changes

### PR DESCRIPTION
**Pull request by wwhchung**
Use actual token ranges in the Grouping for better readability.
Remove unused CONTRACT_URI
Add EIP2981
Revert if tokenURI requested on invalid token
Add provenance hash
Remove redundant committed variable.
Use mint rather than safeMint (cheaper and unecessary to use safeMint)

Add a number of testing (testing negative cases)

### CODE REVIEW

**Comment by wwhchung** [comment]
This is still missing tests for minting over multiple transactions, and checking you can't over-mint

**Comment by wwhchung** [comment]
Unfortunately I don't have any more time to dig into this too deeply, but I would highly suggest testing various airdrop variations, including the offset functions as expected (you can check via the tokenURI and owner of tokens)

**Comment by mouse-dev-1** [comment]
I would rather not change the indices as that has the ability to reintroduce off-by-one errors. I will add royalties, and reverting tokenURI. Will speak to team about a provenance hash. CONTRACT_URI remains because I wanted to ensure compatibility with marketplaces, maybe unnecessary and redundant. Committed is not redundant as the deployer should not be allowed to re-commit which could allow for the deployer to choose a different target block hash should it be undesirable, just added a check to ensure committed is false at the time of commit.

**Comment by mouse-dev-1** [comment]
On second review, I see your point about the committed var. I have included your changes.

**Comment by wwhchung** [comment]
There’s no off by one error though. You only use the end index in one variable computation and it was adjusted appropriately. The overlapping indexes is a bit confusing tbh. 

But in any event I suggest you add test coverage for different airdrop combinations and check mint order based on the selected shift offset

**Pull request closed without merging**
