### PR TITLE
Clean random seed and allow 0 shift

### PR DESCRIPTION
**Pull request by ghost**
Calculation at this point is unnecessary because of the modulus on line 80
0 is a valid shift if that's how the numbers fall, it should not be forced to always shift at least 1

### CODE REVIEW

**Comment by 0xildefonso** [comment]
lgtm

**Review by mouse-dev-1 — CHANGES_REQUESTED** [review]
This would not work because airdrop() requires shiftQuantity to be greater than 0. If it is not the contract becomes unusable.

**Comment by wyecompany** [comment]
> This would not work because airdrop() requires shiftQuantity to be greater than 0. If it is not the contract becomes unusable.

If somehow the uint256 of the blockhash turned out to be 0, this function could be run again thus it could not lock up the contract

**Comment by wyecompany** [comment]
believe a similar change has been proposed by manifold anyway

**Pull request closed without merging**
